import React, { createContext, useContext, useState } from "react";

export const translations = {
  en: {
    appName: "LearnAgent",
    language: "中文",
    dashboard: "Dashboard",
    dailyCheckin: "Daily Check-in",
    errorBook: "Error Book",
    fullPlan: "Full Plan",
    newPlan: "+ New Learning Plan",
    loginDesc: "Sign in to access your learning plans",
    loginBtn: "Sign In to Continue",
    // Profile
    completeProfile: "Complete Your Profile",
    completeProfileDesc: "Please provide your contact details to continue",
    phoneNumber: "Phone Number",
    phonePlaceholder: "+1 234 567 8900",
    saveProfile: "Save & Continue",
    savingProfile: "Saving...",
    // Setup
    setupBadge: "Learning Check-in Agent",
    setupTitle: "Set Up Your Learning Plan",
    setupDesc: "Configure your study parameters and we'll generate a complete learning roadmap with daily check-ins",
    logicPlannerStep: "Logic Planner",
    contentGeneratorStep: "Content Generator",
    summaryPushStep: "Summary & Push",
    waitMsg: "Running multi-model AI pipeline. Please wait...",
    goToDashboard: "Go to Dashboard →",
    // Setup form
    back: "Back",
    continue: "Continue",
    generatePlan: "Generate Learning Plan",
    generatingPlan: "Generating Plan...",
    stepLabel: "Step",
    ofLabel: "of",
    fieldProgramName: "Learning Program",
    fieldProgramDesc: "Full name including exam system",
    fieldProgramPlaceholder: "e.g. NEC Economics Competition, AP Macroeconomics, IB Mathematics AA HL, A-Level Chemistry AS",
    fieldFoundation: "Current Foundation",
    fieldFoundationDesc: "What you've mastered, completed stages, current level",
    fieldFoundationPlaceholder: "e.g. Completed AP Microeconomics full content, zero foundation, completed IGCSE core content",
    fieldDuration: "Planned Total Duration",
    fieldDurationDesc: "Total preparation period, accurate to weeks/months",
    fieldDurationPlaceholder: "e.g. 2 months (8 weeks), 3 months (12 weeks), 6 weeks",
    fieldStartDate: "Start Date",
    fieldStartDateDesc: "When do you want to start?",
    fieldMinGoal: "Minimum Goal",
    fieldMinGoalDesc: "Definite, quantifiable minimum target matching official standards",
    fieldMinGoalPlaceholder: "e.g. 100% coverage of DR Group test points, ≥85% daily accuracy, AP score of 5",
    fieldSprintGoal: "Sprint Goal",
    fieldSprintGoalDesc: "Clear, quantifiable elevated target (must be higher than minimum)",
    fieldSprintGoalPlaceholder: "e.g. 80% mastery of AS group advanced points, ≥75% accuracy",
    fieldDailyMins: "Daily Available Duration (minutes)",
    fieldDailyMinsDesc: "Fixed daily study time, accurate to minutes",
    fieldDailyMinsPlaceholder: "e.g. 60",
    conflictTitle: "Conflict Avoidance Period",
    conflictDesc: "Specify any time periods where you need to avoid intensive study (e.g., major exams). Optional.",
    conflictStartDate: "Start Date",
    conflictEndDate: "End Date",
    conflictReason: "Reason",
    conflictReasonPlaceholder: "e.g. AP major exam period, school mock exams",
    // Dashboard
    noActivePlan: "No Active Learning Plan",
    noActivePlanDesc: "Set up your first learning plan to get started",
    createPlan: "Create Learning Plan",
    minimumGoal: "Minimum Goal",
    sprintGoal: "Sprint Goal",
    dailyTime: "Daily Time",
    startDate: "Start Date",
    daysStudied: "Days Studied",
    errorsToReview: "Errors to Review",
    recentCheckins: "Recent Check-ins",
    intensivePhase: "📘 Intensive Phase",
    conflictAvoidancePhase: "🛡️ Conflict Avoidance",
    finalSprintPhase: "🚀 Final Sprint",
    submitAnswers: "Submit your answers",
    viewGrading: "View grading results",
    generateNext: "Generate next day",
    startLearning: "Start today's learning",
    // Daily check-in
    lessonTab: "📖 Lesson",
    submitAnswersTab: "📝 Submit Answers",
    gradingTab: "📊 Grading Results",
    statusDone: "✅ Complete",
    statusAwaiting: "📝 Awaiting Answers",
    statusGrading: "📊 Grading",
    basicLabel: "Basic:",
    advancedLabel: "Advanced:",
    consolidationWarning: "⚠️ Tomorrow: Consolidation Day",
    noActivePlanFound: "No active plan found",
    createAPlan: "Create a Plan",
    readyToStart: "Ready to start your first day of learning",
    generateDay1: "Generate Day 1 Content",
    generateDayN: "Generate Day",
    contentLabel: "Content",
    dayLabel: "Day",
    genLogic: "🧠 Step 1/3: Logic Planner (Gemini) building schedule...",
    genContent: "📚 Step 2/3: Content Generator (Claude) writing lesson...",
    genSummary: "✨ Step 3/3: Summary model formatting output...",
    genConflict: "🛡️ Generating lightweight conflict avoidance content...",
    genGrading: "📊 Grading your answers (Claude)...",
    // Error book
    errorsTitle: "Error Book",
    highFreqPoints: "High-Frequency Error Points",
    filterAll: "All",
    filterPending: "Pending Review",
    filterReviewed: "Reviewed",
    filterBasic: "Basic",
    filterAdvanced: "Advanced",
    noErrors: "No errors recorded yet",
    // Plan view
    viewFullPlan: "Full Learning Plan",
    noPlan: "No plan found",
    goSetup: "Go to Setup",
  },
  zh: {
    appName: "学习助手",
    language: "English",
    dashboard: "仪表盘",
    dailyCheckin: "每日打卡",
    errorBook: "错题本",
    fullPlan: "完整计划",
    newPlan: "+ 新建学习计划",
    loginDesc: "登录以访问你的学习计划",
    loginBtn: "立即登录",
    // Profile
    completeProfile: "完善个人资料",
    completeProfileDesc: "请填写联系方式以继续使用",
    phoneNumber: "手机号码",
    phonePlaceholder: "+86 138 0000 0000",
    saveProfile: "保存并继续",
    savingProfile: "保存中...",
    // Setup
    setupBadge: "学习打卡助手",
    setupTitle: "设置你的学习计划",
    setupDesc: "配置你的学习参数，我们将生成完整的学习路线图和每日打卡内容",
    logicPlannerStep: "逻辑规划",
    contentGeneratorStep: "内容生成",
    summaryPushStep: "总结推送",
    waitMsg: "正在运行多模型AI流水线，请稍候...",
    goToDashboard: "前往仪表盘 →",
    // Setup form
    back: "返回",
    continue: "继续",
    generatePlan: "生成学习计划",
    generatingPlan: "生成中...",
    stepLabel: "第",
    ofLabel: "步，共",
    fieldProgramName: "学习项目",
    fieldProgramDesc: "完整名称，包括考试体系",
    fieldProgramPlaceholder: "例如：NEC经济竞赛、AP宏观经济、IB数学AA HL、A-Level化学AS",
    fieldFoundation: "现有基础",
    fieldFoundationDesc: "已掌握的内容、完成的阶段、当前水平",
    fieldFoundationPlaceholder: "例如：已完成AP微观经济全部内容、零基础、已完成IGCSE核心内容",
    fieldDuration: "计划总时长",
    fieldDurationDesc: "总备考周期，精确到周/月",
    fieldDurationPlaceholder: "例如：2个月（8周）、3个月（12周）、6周",
    fieldStartDate: "开始日期",
    fieldStartDateDesc: "你想从哪天开始？",
    fieldMinGoal: "最低目标",
    fieldMinGoalDesc: "明确可量化的最低目标，符合官方标准",
    fieldMinGoalPlaceholder: "例如：DR组考点100%覆盖，每日正确率≥85%，AP考5分",
    fieldSprintGoal: "冲刺目标",
    fieldSprintGoalDesc: "明确可量化的进阶目标（必须高于最低目标）",
    fieldSprintGoalPlaceholder: "例如：AS组进阶考点80%掌握，正确率≥75%",
    fieldDailyMins: "每日可用时长（分钟）",
    fieldDailyMinsDesc: "固定每日学习时间，精确到分钟",
    fieldDailyMinsPlaceholder: "例如：60",
    conflictTitle: "隔热期设置",
    conflictDesc: "指定需要避免高强度学习的时间段，例如重要考试期间。可选填。",
    conflictStartDate: "开始日期",
    conflictEndDate: "结束日期",
    conflictReason: "原因",
    conflictReasonPlaceholder: "例如：AP主要考试期、学校模拟考",
    // Dashboard
    noActivePlan: "暂无活跃学习计划",
    noActivePlanDesc: "创建你的第一个学习计划以开始使用",
    createPlan: "创建学习计划",
    minimumGoal: "最低目标",
    sprintGoal: "冲刺目标",
    dailyTime: "每日时长",
    startDate: "开始日期",
    daysStudied: "已学天数",
    errorsToReview: "待复习错题",
    recentCheckins: "最近打卡记录",
    intensivePhase: "📘 强化阶段",
    conflictAvoidancePhase: "🛡️ 隔热阶段",
    finalSprintPhase: "🚀 冲刺阶段",
    submitAnswers: "提交你的答案",
    viewGrading: "查看批改结果",
    generateNext: "生成下一天",
    startLearning: "开始今日学习",
    // Daily check-in
    lessonTab: "📖 今日课程",
    submitAnswersTab: "📝 提交答案",
    gradingTab: "📊 批改结果",
    statusDone: "✅ 已完成",
    statusAwaiting: "📝 待提交",
    statusGrading: "📊 批改中",
    basicLabel: "基础题：",
    advancedLabel: "进阶题：",
    consolidationWarning: "⚠️ 明日：巩固日",
    noActivePlanFound: "未找到活跃计划",
    createAPlan: "创建计划",
    readyToStart: "准备好开始你的第一天学习了",
    generateDay1: "生成第1天内容",
    generateDayN: "生成第",
    contentLabel: "内容",
    dayLabel: "第",
    genLogic: "🧠 步骤 1/3：逻辑规划模型（Gemini）生成课程安排...",
    genContent: "📚 步骤 2/3：内容生成模型（Claude）生成今日课程...",
    genSummary: "✨ 步骤 3/3：总结模型整理输出...",
    genConflict: "🛡️ 正在生成隔热期轻量内容...",
    genGrading: "📊 正在批改你的答案（Claude）...",
    // Error book
    errorsTitle: "错题本",
    highFreqPoints: "高频错误考点",
    filterAll: "全部",
    filterPending: "待复习",
    filterReviewed: "已复习",
    filterBasic: "基础题",
    filterAdvanced: "进阶题",
    noErrors: "暂无错题记录",
    // Plan view
    viewFullPlan: "完整学习计划",
    noPlan: "未找到计划",
    goSetup: "前往设置",
  },
};

const LanguageContext = createContext({ lang: "en", t: translations.en, toggleLang: () => {} });

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem("lang") || "en"; } catch { return "en"; }
  });

  const toggleLang = () => {
    const next = lang === "en" ? "zh" : "en";
    setLang(next);
    try { localStorage.setItem("lang", next); } catch {}
  };

  return (
    <LanguageContext.Provider value={{ lang, t: translations[lang], toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}